version: '3.8'

services:
  db: 
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
     - backend
  redis: 
    container_name: redis
    image: redis:5.0
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
     - backend

volumes:
  postgres_data:
  redis_data:
networks:
  backend:
    driver: bridge